name: MovieBoxApp
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "16.0" # مهم جداً لدعم ميزة رفع الترجمة
  xcodeVersion: "15.0"
targets:
  MovieBoxApp:
    type: application
    platform: iOS
    sources:
      - path: MovieBoxApp
    settings:
      base:
        INFOPLIST_FILE: MovieBoxApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.MovieBoxApp # غيّر yourname لاسمك
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1" # 1 تعني آيفون فقط
